export const ACHIEVEMENTS = [
  // ── Bananes totales ──────────────────────────────────────────
  {
    id: 'first_banana',
    name: 'Premier régime',
    description: 'Gagner 1 banane.',
    flavor: 'Un voyage de mille bananes commence par un seul clic.',
    emoji: '🍌', pixelId: 'banana', category: 'bananes',
    condition: s => s.totalBananas >= 1,
  },
  {
    id: 'hundred_bananas',
    name: 'Petit-déjeuner de singe',
    description: 'Accumuler 100 bananes au total.',
    flavor: 'C\'est un bon début. Enfin, pour un singe.',
    emoji: '🥣', pixelId: 'bowl', category: 'bananes',
    condition: s => s.totalBananas >= 100,
  },
  {
    id: 'thousand_bananas',
    name: 'Garde-manger bien rempli',
    description: 'Accumuler 1 000 bananes au total.',
    flavor: 'Ta maison sent fort.',
    emoji: '📦', pixelId: 'box', category: 'bananes',
    condition: s => s.totalBananas >= 1000,
  },
  {
    id: 'ten_k_bananas',
    name: 'Grossiste en bananes',
    description: 'Accumuler 10 000 bananes au total.',
    flavor: 'Tu pourrais en vendre. Mais tu ne le feras pas.',
    emoji: '🏪', pixelId: 'store', category: 'bananes',
    condition: s => s.totalBananas >= 10000,
  },
  {
    id: 'hundred_k_bananas',
    name: 'Magnat de la banane',
    description: 'Accumuler 100 000 bananes au total.',
    flavor: 'Quelqu\'un devrait appeler un médecin.',
    emoji: '💼', pixelId: 'briefcase', category: 'bananes',
    condition: s => s.totalBananas >= 100000,
  },
  {
    id: 'million_bananas',
    name: 'Milliardaire jaune',
    description: 'Accumuler 1 000 000 bananes au total.',
    flavor: 'Tu aurais pu acheter une maison. Tu as préféré ça.',
    emoji: '💰', pixelId: 'money', category: 'bananes',
    condition: s => s.totalBananas >= 1000000,
  },
  {
    id: 'ten_million_bananas',
    name: 'La banane est ta religion',
    description: 'Accumuler 10 000 000 bananes au total.',
    flavor: 'Il n\'y a plus rien à dire.',
    emoji: '🙏', pixelId: 'pray', category: 'bananes',
    condition: s => s.totalBananas >= 10000000,
  },

  // ── Clics ────────────────────────────────────────────────────
  {
    id: 'first_click',
    name: 'Le début de la fin',
    description: 'Cliquer pour la première fois.',
    flavor: 'Tu ne reviendras plus jamais en arrière.',
    emoji: '☝', pixelId: 'finger', category: 'clics',
    condition: s => s.totalClicks >= 1,
  },
  {
    id: 'fifty_clicks',
    name: 'Cliqueur débutant',
    description: 'Cliquer 50 fois.',
    flavor: 'C\'est mignon.',
    emoji: '🖱', pixelId: 'mouse', category: 'clics',
    condition: s => s.totalClicks >= 50,
  },
  {
    id: 'five_hundred_clicks',
    name: 'Cliqueur acharné',
    description: 'Cliquer 500 fois.',
    flavor: 'Ton doigt commence à avoir son propre avis.',
    emoji: '💪', pixelId: 'muscle', category: 'clics',
    condition: s => s.totalClicks >= 500,
  },
  {
    id: 'two_k_clicks',
    name: 'Tendinite garantie',
    description: 'Cliquer 2 000 fois.',
    flavor: 'Consulte un médecin. Il te dira d\'arrêter.',
    emoji: '💊', pixelId: 'pill', category: 'clics',
    condition: s => s.totalClicks >= 2000,
  },
  {
    id: 'ten_k_clicks',
    name: 'RSI niveau dieu',
    description: 'Cliquer 10 000 fois.',
    flavor: 'Ton index mérite une retraite.',
    emoji: '🏥', pixelId: 'hospital', category: 'clics',
    condition: s => s.totalClicks >= 10000,
  },
  {
    id: 'frenzy',
    name: 'Frénésie bananière',
    description: 'Cliquer 10 fois en moins de 2 secondes.',
    flavor: 'Tu n\'es plus un singe. Tu es une machine.',
    emoji: '⚡', pixelId: 'lightning', category: 'clics',
    condition: s => s.frenzy,
  },

  // ── Améliorations ────────────────────────────────────────────
  {
    id: 'first_upgrade',
    name: 'Premier investissement',
    description: 'Acheter une amélioration.',
    flavor: 'L\'économie bananière te remercie.',
    emoji: '🛒', pixelId: 'cart', category: 'upgrades',
    condition: s => s.totalUpgradesBought >= 1,
  },
  {
    id: 'ten_upgrades',
    name: 'Shopaholic simien',
    description: 'Acheter 10 améliorations.',
    flavor: 'Une thérapie serait moins chère (en bananes).',
    emoji: '🛍', pixelId: 'bag', category: 'upgrades',
    condition: s => s.totalUpgradesBought >= 10,
  },
  {
    id: 'twentyfive_upgrades',
    name: 'Addiction au shopping',
    description: 'Acheter 25 améliorations.',
    flavor: 'À ce stade, c\'est pathologique.',
    emoji: '😵', pixelId: 'dizzy', category: 'upgrades',
    condition: s => s.totalUpgradesBought >= 25,
  },
  {
    id: 'all_unlocked',
    name: 'Collectionneur de tout',
    description: 'Acheter chaque amélioration au moins une fois.',
    flavor: 'Tu as tout. Et pourtant, ça ne suffit pas.',
    emoji: '🏆', pixelId: 'trophy', category: 'upgrades',
    condition: s => Object.values(s.upgradeCounts).every(c => c >= 1),
  },
  {
    id: 'obsessed',
    name: 'Obsessionnel',
    description: 'Avoir 10 exemplaires d\'une même amélioration.',
    flavor: 'Plus c\'est pareil, plus c\'est bien.',
    emoji: '🔁', pixelId: 'arrows', category: 'upgrades',
    condition: s => Object.values(s.upgradeCounts).some(c => c >= 10),
  },

  // ── Passif ───────────────────────────────────────────────────
  {
    id: 'passive_1',
    name: 'Le singe paresseux',
    description: 'Atteindre 1 banane/seconde.',
    flavor: 'Les bananes arrivent même quand tu ne fais rien. Comme dans la vie.',
    emoji: '😴', pixelId: 'sleeping', category: 'passif',
    condition: s => s.passive >= 1,
  },
  {
    id: 'passive_10',
    name: 'Empire bananier',
    description: 'Atteindre 10 bananes/seconde.',
    flavor: 'Un petit empire pour un singe, un grand empire pour l\'humanité.',
    emoji: '🌍', pixelId: 'earth', category: 'passif',
    condition: s => s.passive >= 10,
  },
  {
    id: 'passive_100',
    name: 'Machine à bananes',
    description: 'Atteindre 100 bananes/seconde.',
    flavor: 'Tu es devenu ce que tu clickais.',
    emoji: '🏭', pixelId: 'factory', category: 'passif',
    condition: s => s.passive >= 100,
  },
  {
    id: 'passive_1000',
    name: 'Tsunami bananier',
    description: 'Atteindre 1 000 bananes/seconde.',
    flavor: 'Personne ne peut t\'arrêter.',
    emoji: '🌊', pixelId: 'wave', category: 'passif',
    condition: s => s.passive >= 1000,
  },

  // ── Prestige ─────────────────────────────────────────────────
  {
    id: 'first_prestige',
    name: 'Nouveau départ',
    description: 'Effectuer ton premier prestige.',
    flavor: 'Tu as tout abandonné pour recommencer. Sage décision.',
    emoji: '♻', pixelId: 'recycle', category: 'prestige',
    condition: s => s.prestigeLevel >= 1,
  },
  {
    id: 'five_prestiges',
    name: 'Boucle infernale',
    description: 'Effectuer 5 prestiges.',
    flavor: 'La folie, c\'est de faire la même chose en espérant un résultat différent.',
    emoji: '🔄', pixelId: 'cycle', category: 'prestige',
    condition: s => s.prestigeLevel >= 5,
  },
  {
    id: 'ten_prestiges',
    name: 'Sisyphe bananier',
    description: 'Effectuer 10 prestiges.',
    flavor: 'Sisyphe avait son rocher. Tu as ta banane.',
    emoji: '🗻', pixelId: 'mountain', category: 'prestige',
    condition: s => s.prestigeLevel >= 10,
  },

  // ── Événements ───────────────────────────────────────────────
  {
    id: 'first_event',
    name: 'Imprévu',
    description: 'Vivre ton premier événement aléatoire.',
    flavor: 'La vie est pleine de surprises. Certaines volent tes bananes.',
    emoji: '🎲', pixelId: 'dice', category: 'events',
    condition: s => s.eventsEncountered >= 1,
  },
  {
    id: 'ten_events',
    name: 'Vétéran des caprices',
    description: 'Vivre 10 événements aléatoires.',
    flavor: 'Tu ne te laisses plus surprendre. Enfin presque.',
    emoji: '🎯', pixelId: 'target', category: 'events',
    condition: s => s.eventsEncountered >= 10,
  },
  {
    id: 'golden_first',
    name: 'Réflexes de singe',
    description: 'Cliquer sur une banane dorée.',
    flavor: 'Tu l\'as vue. Tu l\'as voulue. Tu l\'as eue.',
    emoji: '⭐', pixelId: 'star', category: 'events',
    condition: s => s.goldenClicked >= 1,
  },
  {
    id: 'golden_five',
    name: 'Chasseur de trésors',
    description: 'Cliquer sur 5 bananes dorées.',
    flavor: 'Les yeux de lynx d\'un primate accompli.',
    emoji: '🌟', pixelId: 'glowstar', category: 'events',
    condition: s => s.goldenClicked >= 5,
  },

  // ── Skins ────────────────────────────────────────────────────
  {
    id: 'first_skin',
    name: 'Fashioniste simien',
    description: 'Acheter ton premier skin.',
    flavor: 'Le style avant tout. Avant les bananes, même.',
    emoji: '🎨', pixelId: 'palette', category: 'skins',
    condition: s => s.ownedSkins.length >= 2,
  },
  {
    id: 'all_skins',
    name: 'Garde-robe complète',
    description: 'Posséder tous les skins.',
    flavor: 'Un singe bien habillé est un singe heureux.',
    emoji: '👑', pixelId: 'crown', category: 'skins',
    condition: s => s.ownedSkins.length >= 5,
  },

  // ── Secrets absurdes ─────────────────────────────────────────
  {
    id: 'the_answer',
    name: 'La réponse à tout',
    description: '???',
    flavor: 'La réponse à la grande question sur la vie, l\'univers, et le reste. C\'était 42 bananes.',
    emoji: '🎱', pixelId: 'billiard', category: 'secret', secret: true,
    hint: 'Avoir exactement un certain nombre de bananes très philosophique.',
    condition: s => s.hitFortytwo,
  },
  {
    id: 'nice',
    name: 'Nice.',
    description: '???',
    flavor: 'Tu sais ce que tu as fait. On sait tous ce que tu as fait.',
    emoji: '😏', pixelId: 'smirk', category: 'secret', secret: true,
    hint: '...',
    condition: s => s.hitSixtynine,
  },
  {
    id: 'leet',
    name: 'H4x0r de bananes',
    description: '???',
    flavor: '1337 bananes. Tu es officiellement un hacker. De bananes.',
    emoji: '💻', pixelId: 'laptop', category: 'secret', secret: true,
    hint: 'Un certain nombre de bananes qui parle aux initiés d\'internet.',
    condition: s => s.hitLeet,
  },
  {
    id: 'palindrome',
    name: 'Palindromiste',
    description: '???',
    flavor: 'Un nombre qui se lit pareil dans les deux sens. Élégant pour une créature qui mange des bananes.',
    emoji: '🔮', pixelId: 'crystal', category: 'secret', secret: true,
    hint: 'Avoir un nombre de bananes parfaitement symétrique (min. 3 chiffres).',
    condition: s => s.hitPalindrome,
  },
  {
    id: 'midnight',
    name: 'Noctambule',
    description: '???',
    flavor: 'Tu cliques à minuit. Tout va bien. C\'est normal. Continue.',
    emoji: '🌙', pixelId: 'moon', category: 'secret', secret: true,
    hint: 'Cliquer à une heure très particulière de la journée.',
    condition: s => s.midnight,
  },
  {
    id: 'golden_miss',
    name: 'Trop lent',
    description: '???',
    flavor: 'La banane dorée t\'a attendu 10 secondes. Elle est partie. Elle ne reviendra jamais. (Elle reviendra.)',
    emoji: '💨', pixelId: 'wind', category: 'secret', secret: true,
    hint: 'Laisser filer quelque chose de précieux.',
    condition: s => s.goldenExpired,
  },
  {
    id: 'hitchhiker',
    name: 'Obsession de Hitchhiker',
    description: '???',
    flavor: 'Pourquoi 42 fois la même amélioration ? Pourquoi pas.',
    emoji: '🐋', pixelId: 'whale', category: 'secret', secret: true,
    hint: 'Un nombre très spécifique d\'une même amélioration.',
    condition: s => Object.values(s.upgradeCounts).some(c => c >= 42),
  },
  {
    id: 'ermite',
    name: 'Ermite bananier',
    description: '???',
    flavor: 'Cinq minutes sans rien faire. Les bananes poussent quand même. C\'est presque de la poésie.',
    emoji: '🗻', pixelId: 'mountain', category: 'secret', secret: true,
    hint: 'Rester complètement immobile un très long moment.',
    condition: s => s.idleSeconds >= 300,
  },

  // ── Secrets classiques ────────────────────────────────────────
  {
    id: 'broke',
    name: 'Fauché mais heureux',
    description: '???',
    flavor: 'Dépenser jusqu\'au dernier centime, c\'est aussi une forme de sagesse.',
    emoji: '💸', pixelId: 'moneyflight', category: 'secret', secret: true,
    hint: 'Achète tout jusqu\'à avoir 0 banane.',
    condition: s => s.wentBroke,
  },
  {
    id: 'banana_god_unlock',
    name: 'Dieu est jaune',
    description: '???',
    flavor: 'Tu as invoqué le Dieu Banane. Il est déçu que tu n\'aies rien de mieux à faire.',
    emoji: '🏯', pixelId: 'castle', category: 'secret', secret: true,
    hint: 'Débloquer une certaine amélioration divine.',
    condition: s => s.upgradeCounts['banana_god'] >= 1,
  },
  {
    id: 'why',
    name: 'Pourquoi ?',
    description: '???',
    flavor: 'Personne ne peut répondre à cette question.',
    emoji: '❓', pixelId: 'question', category: 'secret', secret: true,
    hint: 'Jouer pendant un certain temps sans rien faire.',
    condition: s => s.idleSeconds >= 120,
  },
  {
    id: 'prestige_rich',
    name: 'Le paradoxe du singe',
    description: '???',
    flavor: 'Tu as tout perdu plusieurs fois, et tu es plus riche que jamais.',
    emoji: '🌀', pixelId: 'vortex', category: 'secret', secret: true,
    hint: 'Prestige avec beaucoup de multiplications derrière toi.',
    condition: s => s.prestigeLevel >= 3 && s.totalBananas >= 5000000,
  },
]

export const CATEGORIES = [
  { id: 'all',      label: 'Tous',          pixelId: null },
  { id: 'bananes',  label: 'Bananes',       pixelId: 'banana' },
  { id: 'clics',    label: 'Clics',         pixelId: 'pointup' },
  { id: 'upgrades', label: 'Upgrades',      pixelId: 'cart' },
  { id: 'passif',   label: 'Passif',        pixelId: 'sleeping' },
  { id: 'prestige', label: 'Prestige',      pixelId: 'recycle' },
  { id: 'events',   label: 'Evénements',    pixelId: 'dice' },
  { id: 'skins',    label: 'Skins',         pixelId: 'palette' },
  { id: 'secret',   label: 'Secrets',       pixelId: 'lock' },
]
